set_property SRC_FILE_INFO {cfile:{D:/Hardware encryption project/hardware-encryption/vivado/hardware-encryption/vivado/Encyption_intpipelined/Encyption_intpipelined.srcs/constrs_1/new/uart.xdc} rfile:../../../Encyption_intpipelined.srcs/constrs_1/new/uart.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{D:/Hardware encryption project/hardware-encryption/vivado/hardware-encryption/vivado/Encyption_intpipelined/Encyption_intpipelined.srcs/constrs_1/new/clock.xdc} rfile:../../../Encyption_intpipelined.srcs/constrs_1/new/clock.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports uart_tx]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports rst_n]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports uart_tx]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports uart_rx]
